#!/bin/bash

# Refreash current branch from remote repo

if [ X"$1" = X"" ]; then
        echo
        echo "Refresh current branch from <remote> repo (fast forward only)."
        echo "Syntax: git-refresh-from <remote>"
        echo
        exit 1
fi

branch_name="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)"

if [ "$branch_name" = "HEAD" ]; then
    echo "Detached head"
    exit 1
else
    echo "git fetch $1 $branch_name"
    (git fetch $1 +$branch_name:refs/remotes/$1/$branch_name &&
     git merge --ff-only refs/remotes/$1/$branch_name &&
     echo "Branch $branch_name was successfully refreshed from $1")
fi

